# Generated by Django 5.0.7 on 2024-07-14 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='release_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
